=pod

=head1 NAME

mtpaint - A simple painting program

=head1 SYNOPSIS

S<mtpaint [option] [imagefile ... ]>

=head1 DESCRIPTION

mtPaint is a simple GTK+1/2 painting program designed for creating icons and pixel based artwork. It can edit indexed palette or 24 bit RGB images and offers basic painting and palette manipulation tools. Its main file format is PNG, although it can also handle JPEG, GIF, TIFF, BMP, XPM, and XBM files. Due to its simplicity and lack of dependencies it runs well on GNU/Linux, Windows and older PC hardware.  There is full documentation of mtPaint's features contained in a handbook.  If you don't already have this, you can download it from the mtPaint website.

=head1 OPTIONS

mtPaint can accept one of the following options:

  --help	Output usage information
  --version	Output version information
  -s		Grab a screenshot
  -v		Start mtPaint in viewer mode


=head1 HOMEPAGE

http://mtpaint.sourceforge.net/

=head1 ORIGINAL AUTHOR

Mark Tyler

The development of mtPaint has been helped by various people from the free software community.  See "Credits" in the README or the mtPaint help system for details.



=cut
