#!/bin/bash
WRKDIR=`pwd`
VERSION=3.40
tar xf mtpaint-$VERSION.tar.bz2
cd mtpaint-$VERSION || exit 1
./configure release intl man staticgif --prefix=/usr --mandir=/usr/man/man1 --docdir=/usr/doc #--fakeroot=$WRKDIR/slacklibs
make
DEST=$WRKDIR/zad
make install DESTDIR=$DEST
gzip -9 $DEST/usr/man/man*/*
cd $WRKDIR
unzip mtpaint_handbook-$VERSION.zip
mkdir -p $DEST/usr/doc
mv mtpaint_handbook-$VERSION/docs $DEST/usr/doc/mtpaint
cd $DEST || exit 1
makepkg -l y -c y $WRKDIR/mtpaint-${VERSION}-i386-1_slack12.1.tgz
